chore: ci auto release

diff --git a/.github/workflows/create-bumb-version-pr.yml b/.github/workflows/create-bumb-version-pr.yml
--- a/.github/workflows/create-bumb-version-pr.yml
+++ b/.github/workflows/create-bumb-version-pr.yml
@@ -2,25 +2,25 @@ name: Create bump version PR
 
 on:
   workflow_dispatch:
-    inputs:
-      branche:
-        description: Change version of the branch.
-        default: 'master'
-        type: choice
-        options:
-          - master
-          - beta
-          - alpha
-          - next
-      # version:
-      #   description: Version release as.
-      #   default: 'auto'
-      #   type: choice
-      #   options:
-      #     - auto
-      #     - patch
-      #     - minor
-      #     - major
+    # inputs:
+    #   branche:
+    #     description: Change version of the branch.
+    #     default: 'master'
+    #     type: choice
+    #     options:
+    #       - master
+    #       - beta
+    #       - alpha
+    #       - next
+    # version:
+    #   description: Version release as.
+    #   default: 'auto'
+    #   type: choice
+    #   options:
+    #     - auto
+    #     - patch
+    #     - minor
+    #     - major
 
 concurrency: ${{ github.workflow }}-${{ github.ref }}
 
@@ -35,7 +35,7 @@ jobs:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
-          ref: ${{ inputs.branche }}
+          # ref: ${{ inputs.branche }}
 
       - name: Install dependencies
         uses: ./.github/actions/prepare-install
@@ -45,12 +45,25 @@ jobs:
       - name: Pre build ckeck
         run: pnpm build
 
-      - name: Create Pull Request
+      - name: Create Version Pull Request
+        id: changesets
         uses: changesets/action@v1
         with:
           version: changeset version
           commit: 'chore: version'
           title: 'chore: version'
-          setupGitUser: 'github-actions[changeset]'
+          setupGitUser: true
+          createGithubReleases: false
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: After changesets
+        run: |
+          if [[ ${{ steps.changesets.outputs.hasChangesets }} == false ]]; then
+            # No changesets
+            echo "::error title=No changesets found::All changesets are empty, not creating PR, please add changeset"
+            exit 1
+          else
+            # Created Pull Request
+            echo "::notice title=PR is created::Created bump version PR address is: https://github.com/${{github.repository}}/pull/${{steps.changesets.outputs.pullRequestNumber}}"
+          fi
diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -7,17 +7,22 @@ on:
 
 jobs:
   release:
-    # created chore: bump version PR by changesets bot
+    # created version approved PR by changesets bot or manual dispatch
     if: |
-      github.event.pull_request.user == 'github-actions[changeset]' &&
-      github.event.pull_request.title == 'chore: version' &&
-      github.event.review.state == 'APPROVED'
+      (
+        github.event_name == 'pull_request_review' &&
+        github.event.pull_request.user.type == 'Bot' &&
+        startswith(github.event.pull_request.head.ref, 'changeset-release/') &&
+        github.event.review.state == 'APPROVED'
+      ) ||
+      github.event_name == 'workflow_dispatch'
     runs-on: ubuntu-latest
     strategy:
       matrix:
         node-version: [18.x]
     outputs:
       published: ${{ steps.changesets.outputs.published }}
+      hasChangesets: ${{ steps.changesets.outputs.hasChangesets }}
       publishedPackages: ${{ steps.changesets.outputs.publishedPackages }}
 
     steps:
@@ -27,7 +32,7 @@ jobs:
         with:
           node-version: ${{ matrix.node-version }}
 
-      # 发布开始通知
+      # release start notify
       - name: Release start ding talk dev group notify
         uses: zcong1993/actions-ding@master
         with:
@@ -51,21 +56,20 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
         with:
-          publish: |
-            pnpm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
-            pnpm publish-packages
+          publish: pnpm publish-package
           createGithubReleases: true
 
-  # 发布成功
+  # when release successful
   release-succeeded:
     needs: release
     if: needs.release.outputs.published == 'true'
     runs-on: ubuntu-latest
     steps:
       - name: Release succeeded comment
+        if: github.event_name == 'pull_request_review'
         uses: peter-evans/create-or-update-comment@v4
         with:
-          issue-number: 1
+          issue-number: ${{ github.event.pull_request.number }}
           body: |
             Released to successful 🎉
 
@@ -79,18 +83,21 @@ jobs:
           reactions: 'rocket'
 
       - name: automerge
+        if: github.event_name == 'pull_request_review'
         uses: 'pascalgn/automerge-action@v0.16.2'
         env:
+          MERGE_LABELS: ''
+          PULL_REQUEST: ${{ github.event.pull_request.number }}
           MERGE_METHOD: 'squash'
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-  # 发布失败
+  # when release failed
   release-failed:
     needs: release
     if: needs.release.outputs.published != 'true'
     runs-on: ubuntu-latest
     steps:
-      # 发布失败通知开发群
+      # release failed notify
       - name: Release failed ding talk dev group notify
         uses: zcong1993/actions-ding@master
         with:
@@ -106,3 +113,14 @@ jobs:
                 "picUrl": "https://gw.alipayobjects.com/mdn/antv_site/afts/img/A*o40BRo-ANLoAAAAAAAAAAABkARQnAQ"
               }
             }
+
+      - name: Released err message
+        run: |
+          if [[ ${{ needs.release.outputs.hasChangesets }} == false ]]; then
+            # No changesets
+            echo "::error title=No changesets found::All changesets are empty, not creating PR, please add changeset"
+          else
+            # Released failed
+            echo "::error title=Publish failed::Released NPM or Github failed"
+          fi
+          exit 1
